name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "6,26,46 * * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
      - name: Fetch latest data
        run: |-
          curl --request GET \
            --url 'https://footballapi.pulselive.com/football/fixtures?statuses=U%2CL%2CC&pageSize=10&page=0&gameweeks=12269&altIds=true&live=true' \
            --header 'accept: */*' \
            --header 'accept-language: en-US,en;q=0.9,id-ID;q=0.8,id;q=0.7' \
            --header 'authority: footballapi.pulselive.com' \
            --header 'content-type: application/x-www-form-urlencoded; charset=UTF-8' \
            --header 'if-none-match: W/"03b2b9bb2d61e889c39f3fa9353769d4a"' \
            --header 'origin: https://www.premierleague.com' \
            --header 'referer: https://www.premierleague.com/' \
            --header 'sec-ch-ua: "Not/A)Brand";v="99", "Google Chrome";v="115", "Chromium";v="115"' \
            --header 'sec-ch-ua-mobile: ?0' \
            --header 'sec-ch-ua-platform: "macOS"' \
            --header 'sec-fetch-dest: empty' \
            --header 'sec-fetch-mode: cors' \
            --header 'sec-fetch-site: cross-site' \
            --header 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36' | jq > fixtures.json
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          sh format-table.sh
          sh format-standing.sh
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
